import type { Appointment } from "./types";

export const appointmentQuickActions = [
  "Remarcar atendimento",
  "Enviar lembrete",
  "Abrir perfil do paciente",
  "Copiar link da sessão",
];

export const appointments: Appointment[] = [
  {
    id: "apt-001",
    date: "2026-03-09",
    dateLabel: "09 de março de 2026",
    time: "09:00",
    timeLabel: "09:00 às 09:50",
    duration: 50,
    durationLabel: "50 minutos",
    patientName: "Mariana Silva",
    modalityLabel: "Online",
    sessionTypeLabel: "Retorno",
    appointmentStatusLabel: "Confirmado",
    appointmentStatusVariant: "success",
    paymentStatusLabel: "Pago",
    paymentStatusVariant: "success",
    meetingLink: "https://meet.google.com/abc-defg-hij",
    notes: "Paciente pediu recibo após a sessão. Confirmar presença na véspera.",
    patient: {
      fullName: "Mariana Silva",
      phone: "(31) 99999-9999",
      email: "mariana.silva@email.com",
      typeLabel: "Paciente recorrente",
    },
    payment: {
      amountLabel: "R$ 100,00",
      methodLabel: "PIX",
      statusLabel: "Pago",
      statusVariant: "success",
      paidAtLabel: "09/03/2026 às 08:12",
    },
    activityTimeline: [
      {
        id: 1,
        title: "Agendamento criado",
        description: "Sessão agendada manualmente pela terapeuta.",
        timeLabel: "08/03/2026 · 18:42",
      },
      {
        id: 2,
        title: "Pagamento aprovado",
        description: "Pagamento via PIX confirmado com sucesso.",
        timeLabel: "09/03/2026 · 08:12",
      },
      {
        id: 3,
        title: "Confirmação enviada",
        description: "Mensagem de confirmação enviada para a paciente.",
        timeLabel: "09/03/2026 · 08:15",
      },
    ],
  },
  {
    id: "apt-002",
    date: "2026-03-09",
    dateLabel: "09 de março de 2026",
    time: "10:30",
    timeLabel: "10:30 às 11:20",
    duration: 50,
    durationLabel: "50 minutos",
    patientName: "Carlos Eduardo Santos",
    modalityLabel: "Presencial",
    sessionTypeLabel: "Retorno",
    appointmentStatusLabel: "Confirmado",
    appointmentStatusVariant: "success",
    paymentStatusLabel: "Pendente",
    paymentStatusVariant: "warning",
    notes: "Trazer comprovante da última sessão.",
    patient: {
      fullName: "Carlos Eduardo Santos",
      phone: "(31) 98888-2222",
      email: "carlos.santos@email.com",
      typeLabel: "Paciente recorrente",
    },
    payment: {
      amountLabel: "R$ 100,00",
      methodLabel: "Link de pagamento",
      statusLabel: "Pendente",
      statusVariant: "warning",
    },
    activityTimeline: [
      {
        id: 1,
        title: "Agendamento criado",
        description: "Sessão agendada pela terapeuta.",
        timeLabel: "08/03/2026 · 20:10",
      },
    ],
  },
  {
    id: "apt-003",
    date: "2026-03-09",
    dateLabel: "09 de março de 2026",
    time: "14:00",
    timeLabel: "14:00 às 14:50",
    duration: 50,
    durationLabel: "50 minutos",
    patientName: "Júlia Oliveira",
    modalityLabel: "Online",
    sessionTypeLabel: "Primeira Sessão",
    appointmentStatusLabel: "Confirmado",
    appointmentStatusVariant: "success",
    paymentStatusLabel: "Pago",
    paymentStatusVariant: "success",
    meetingLink: "https://meet.google.com/jul-olia-123",
    patient: {
      fullName: "Júlia Oliveira",
      phone: "(31) 97777-3333",
      email: "julia.oliveira@email.com",
      typeLabel: "Primeira consulta",
    },
    payment: {
      amountLabel: "R$ 120,00",
      methodLabel: "PIX",
      statusLabel: "Pago",
      statusVariant: "success",
      paidAtLabel: "08/03/2026 às 19:20",
    },
    activityTimeline: [
      {
        id: 1,
        title: "Reserva convertida em agendamento",
        description: "Pagamento confirmado e sessão liberada.",
        timeLabel: "08/03/2026 · 19:20",
      },
    ],
  },
  {
    id: "apt-004",
    date: "2026-03-09",
    dateLabel: "09 de março de 2026",
    time: "16:00",
    timeLabel: "16:00 às 16:50",
    duration: 50,
    durationLabel: "50 minutos",
    patientName: "Roberto Almeida",
    modalityLabel: "Presencial",
    sessionTypeLabel: "Retorno",
    appointmentStatusLabel: "Confirmado",
    appointmentStatusVariant: "success",
    paymentStatusLabel: "Pago",
    paymentStatusVariant: "success",
    patient: {
      fullName: "Roberto Almeida",
      phone: "(31) 96666-1111",
      email: "roberto.almeida@email.com",
      typeLabel: "Paciente recorrente",
    },
    payment: {
      amountLabel: "R$ 100,00",
      methodLabel: "Dinheiro",
      statusLabel: "Pago",
      statusVariant: "success",
      paidAtLabel: "09/03/2026 às 15:40",
    },
    activityTimeline: [
      {
        id: 1,
        title: "Agendamento confirmado",
        description: "Sessão confirmada manualmente.",
        timeLabel: "09/03/2026 · 15:40",
      },
    ],
  },
  {
    id: "apt-005",
    date: "2026-03-10",
    dateLabel: "10 de março de 2026",
    time: "10:30",
    timeLabel: "10:30 às 11:20",
    duration: 50,
    durationLabel: "50 minutos",
    patientName: "Fernanda Costa",
    modalityLabel: "Online",
    sessionTypeLabel: "Retorno",
    appointmentStatusLabel: "Pendente",
    appointmentStatusVariant: "warning",
    paymentStatusLabel: "Pendente",
    paymentStatusVariant: "warning",
    patient: {
      fullName: "Fernanda Costa",
      phone: "(31) 95555-4444",
      email: "fernanda.costa@email.com",
      typeLabel: "Paciente recorrente",
    },
    payment: {
      amountLabel: "R$ 100,00",
      methodLabel: "Link de pagamento",
      statusLabel: "Pendente",
      statusVariant: "warning",
    },
    activityTimeline: [
      {
        id: 1,
        title: "Pré-reserva criada",
        description: "Aguardando confirmação do pagamento.",
        timeLabel: "09/03/2026 · 17:00",
      },
    ],
  },
];